```yaml
services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.12.3
    container_name: nginx-proxy-manager
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./NGINX_Proxy_Manager/data:/data
      - ./NGINX_Proxy_Manager/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
```
